name: Run ChAI Test

on: 
  push:
    branches: [ main, im-dev ]
  pull_request:
    branches: [ main, im-dev ]


jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Numerical Correspondence Testing Job
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run root docker action step
        uses: ./.github/actions/main-docker # Uses an action in the root directory
        id: hello-docker
