name: Test Docker Image Action (Hello Action)

on: 
  push:
    branches: [ main, iain-changes ]
  pull_request:
    branches: [ main, iain-changes ]


jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hello world action step
        uses: ./../.github/actions/hello-action # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'

      # Use the output from the `hello` step
      - name: Get the output time
        run: |
          echo "The time was ${{ steps.hello.outputs.time }}"
          (echo "The python3 path is ${{ steps.hello.outputs.python3 }}" || echo "No python3 found!")
          (echo "The chapel path is ${{ steps.hello.outputs.chapel }}" || echo "No chapel found!")

          echo "All outputs: ${{ steps.hello.outputs }}"